// Supabase generated types (will be auto-generated by Supabase CLI)
// This is a placeholder structure until CLI generates the actual types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          timezone: string;
          preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          slug: string;
          description: string | null;
          framework: 'playwright' | 'selenium' | 'cypress' | 'puppeteer' | 'other';
          repository_url: string | null;
          settings: Json;
          status: 'active' | 'archived';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          slug: string;
          description?: string | null;
          framework?: 'playwright' | 'selenium' | 'cypress' | 'puppeteer' | 'other';
          repository_url?: string | null;
          settings?: Json;
          status?: 'active' | 'archived';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          framework?: 'playwright' | 'selenium' | 'cypress' | 'puppeteer' | 'other';
          repository_url?: string | null;
          settings?: Json;
          status?: 'active' | 'archived';
          created_at?: string;
          updated_at?: string;
        };
      };
      uploads: {
        Row: {
          id: string;
          project_id: string;
          user_id: string;
          filename: string;
          file_type: string;
          file_size: number;
          storage_path: string;
          storage_bucket: string;
          mime_type: string | null;
          metadata: Json;
          status: 'pending' | 'processing' | 'completed' | 'failed';
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          project_id: string;
          user_id: string;
          filename: string;
          file_type: string;
          file_size: number;
          storage_path: string;
          storage_bucket: string;
          mime_type?: string | null;
          metadata?: Json;
          status?: 'pending' | 'processing' | 'completed' | 'failed';
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          user_id?: string;
          filename?: string;
          file_type?: string;
          file_size?: number;
          storage_path?: string;
          storage_bucket?: string;
          mime_type?: string | null;
          metadata?: Json;
          status?: 'pending' | 'processing' | 'completed' | 'failed';
          created_at?: string;
          processed_at?: string | null;
        };
      };
      failures: {
        Row: {
          id: string;
          project_id: string;
          upload_id: string | null;
          title: string;
          description: string | null;
          framework: 'playwright' | 'selenium' | 'cypress' | 'puppeteer' | 'other';
          failure_category: 'synchronization' | 'overlay' | 'iframe' | 'stale_element' | 'locator_instability' | 'timeout' | 'api_failure' | 'network' | 'assertion' | 'unknown';
          error_message: string | null;
          stack_trace: string | null;
          test_name: string | null;
          test_file: string | null;
          line_number: number | null;
          browser: string | null;
          os: string | null;
          retry_count: number;
          is_flaky: boolean;
          flakiness_score: number | null;
          raw_data: Json;
          created_at: string;
          first_seen_at: string;
          last_seen_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          upload_id?: string | null;
          title: string;
          description?: string | null;
          framework?: 'playwright' | 'selenium' | 'cypress' | 'puppeteer' | 'other';
          failure_category?: 'synchronization' | 'overlay' | 'iframe' | 'stale_element' | 'locator_instability' | 'timeout' | 'api_failure' | 'network' | 'assertion' | 'unknown';
          error_message?: string | null;
          stack_trace?: string | null;
          test_name?: string | null;
          test_file?: string | null;
          line_number?: number | null;
          browser?: string | null;
          os?: string | null;
          retry_count?: number;
          is_flaky?: boolean;
          flakiness_score?: number | null;
          raw_data?: Json;
          created_at?: string;
          first_seen_at?: string;
          last_seen_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          upload_id?: string | null;
          title?: string;
          description?: string | null;
          framework?: 'playwright' | 'selenium' | 'cypress' | 'puppeteer' | 'other';
          failure_category?: 'synchronization' | 'overlay' | 'iframe' | 'stale_element' | 'locator_instability' | 'timeout' | 'api_failure' | 'network' | 'assertion' | 'unknown';
          error_message?: string | null;
          stack_trace?: string | null;
          test_name?: string | null;
          test_file?: string | null;
          line_number?: number | null;
          browser?: string | null;
          os?: string | null;
          retry_count?: number;
          is_flaky?: boolean;
          flakiness_score?: number | null;
          raw_data?: Json;
          created_at?: string;
          first_seen_at?: string;
          last_seen_at?: string;
        };
      };
      analyses: {
        Row: {
          id: string;
          failure_id: string;
          user_id: string;
          status: 'queued' | 'processing' | 'completed' | 'failed';
          category: 'synchronization' | 'overlay' | 'iframe' | 'stale_element' | 'locator_instability' | 'timeout' | 'api_failure' | 'network' | 'assertion' | 'unknown' | null;
          root_cause: string | null;
          confidence_score: number | null;
          explanation: string | null;
          raw_ai_response: Json | null;
          processing_time_ms: number | null;
          token_usage: number | null;
          model_used: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          failure_id: string;
          user_id: string;
          status?: 'queued' | 'processing' | 'completed' | 'failed';
          category?: 'synchronization' | 'overlay' | 'iframe' | 'stale_element' | 'locator_instability' | 'timeout' | 'api_failure' | 'network' | 'assertion' | 'unknown' | null;
          root_cause?: string | null;
          confidence_score?: number | null;
          explanation?: string | null;
          raw_ai_response?: Json | null;
          processing_time_ms?: number | null;
          token_usage?: number | null;
          model_used?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          failure_id?: string;
          user_id?: string;
          status?: 'queued' | 'processing' | 'completed' | 'failed';
          category?: 'synchronization' | 'overlay' | 'iframe' | 'stale_element' | 'locator_instability' | 'timeout' | 'api_failure' | 'network' | 'assertion' | 'unknown' | null;
          root_cause?: string | null;
          confidence_score?: number | null;
          explanation?: string | null;
          raw_ai_response?: Json | null;
          processing_time_ms?: number | null;
          token_usage?: number | null;
          model_used?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
      };
      recommendations: {
        Row: {
          id: string;
          analysis_id: string;
          type: 'locator_fix' | 'code_fix' | 'retry_strategy' | 'best_practice';
          title: string;
          description: string | null;
          original_code: string | null;
          suggested_code: string | null;
          confidence_score: number | null;
          priority: number;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          analysis_id: string;
          type: 'locator_fix' | 'code_fix' | 'retry_strategy' | 'best_practice';
          title: string;
          description?: string | null;
          original_code?: string | null;
          suggested_code?: string | null;
          confidence_score?: number | null;
          priority?: number;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          analysis_id?: string;
          type?: 'locator_fix' | 'code_fix' | 'retry_strategy' | 'best_practice';
          title?: string;
          description?: string | null;
          original_code?: string | null;
          suggested_code?: string | null;
          confidence_score?: number | null;
          priority?: number;
          metadata?: Json;
          created_at?: string;
        };
      };
      usage_logs: {
        Row: {
          id: string;
          user_id: string;
          project_id: string | null;
          action_type: string;
          resource_type: string | null;
          resource_id: string | null;
          quantity: number;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          project_id?: string | null;
          action_type: string;
          resource_type?: string | null;
          resource_id?: string | null;
          quantity?: number;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          action_type?: string;
          resource_type?: string | null;
          resource_id?: string | null;
          quantity?: number;
          metadata?: Json;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}